#!/bin/bash
# Conda Environment Cleanup Script
# Generated by Conda Environment Optimizer
# Review before executing!

echo "Conda Environment Cleanup Script"
echo "================================"
echo ""
echo "This script will:"
echo "1. Clean conda cache"
echo "2. Remove potentially unused environments"
echo ""
read -p "Do you want to proceed? (yes/no): " confirm

if [ "$confirm" != "yes" ]; then
    echo "Cleanup cancelled."
    exit 0
fi

# Clean conda cache
echo ""
echo "Cleaning conda cache..."
conda clean --all -y

# Remove unused environments (commented out for safety)
echo ""
echo "Potentially unused environments (uncomment to remove):"
# conda env remove -n gemini  # 250.36 MB, 21 packages
# conda env remove -n my_project  # 158.89 MB, 61 packages
# conda env remove -n storyboard  # 116.41 MB, 31 packages

echo ""
echo "Cleanup complete!"
echo "To remove environments, uncomment the lines above and run this script again."
